package com.lti.enums;

public enum InstituteCategory {
	GOVERNMENT_PUBLIC_SECTOR_ORGANISATIONS,
	PRIVATE_SECTOR_ORGANISATIONS,
	HIGHER_EDUCATIONAL_INSTITUTIONS,
	PRE_UNIVERSITY_EDUCATIONAL_INSTITUTIONS
}
